# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sparkapi_session_pb2 as sparkapi__session__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sparkapi_session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SparkApiSessionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.previewDataset = channel.unary_stream(
                '/sparkapisession.SparkApiSession/previewDataset',
                request_serializer=sparkapi__session__pb2.PreviewDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__session__pb2.DatasetRowResponse.FromString,
                _registered_method=True)
        self.summarizeDataset = channel.unary_unary(
                '/sparkapisession.SparkApiSession/summarizeDataset',
                request_serializer=sparkapi__session__pb2.SummarizeDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__session__pb2.PysparkGeneralResponse.FromString,
                _registered_method=True)
        self.loadsDataset = channel.unary_unary(
                '/sparkapisession.SparkApiSession/loadsDataset',
                request_serializer=sparkapi__session__pb2.NewDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__session__pb2.PysparkGeneralResponse.FromString,
                _registered_method=True)
        self.runSql = channel.unary_unary(
                '/sparkapisession.SparkApiSession/runSql',
                request_serializer=sparkapi__session__pb2.SqlRequest.SerializeToString,
                response_deserializer=sparkapi__session__pb2.PysparkTransformResponse.FromString,
                _registered_method=True)
        self.createSession = channel.unary_unary(
                '/sparkapisession.SparkApiSession/createSession',
                request_serializer=sparkapi__session__pb2.NewSessionRequest.SerializeToString,
                response_deserializer=sparkapi__session__pb2.NewSessionResponse.FromString,
                _registered_method=True)


class SparkApiSessionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def previewDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def summarizeDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def loadsDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def runSql(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SparkApiSessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'previewDataset': grpc.unary_stream_rpc_method_handler(
                    servicer.previewDataset,
                    request_deserializer=sparkapi__session__pb2.PreviewDatasetRequest.FromString,
                    response_serializer=sparkapi__session__pb2.DatasetRowResponse.SerializeToString,
            ),
            'summarizeDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.summarizeDataset,
                    request_deserializer=sparkapi__session__pb2.SummarizeDatasetRequest.FromString,
                    response_serializer=sparkapi__session__pb2.PysparkGeneralResponse.SerializeToString,
            ),
            'loadsDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.loadsDataset,
                    request_deserializer=sparkapi__session__pb2.NewDatasetRequest.FromString,
                    response_serializer=sparkapi__session__pb2.PysparkGeneralResponse.SerializeToString,
            ),
            'runSql': grpc.unary_unary_rpc_method_handler(
                    servicer.runSql,
                    request_deserializer=sparkapi__session__pb2.SqlRequest.FromString,
                    response_serializer=sparkapi__session__pb2.PysparkTransformResponse.SerializeToString,
            ),
            'createSession': grpc.unary_unary_rpc_method_handler(
                    servicer.createSession,
                    request_deserializer=sparkapi__session__pb2.NewSessionRequest.FromString,
                    response_serializer=sparkapi__session__pb2.NewSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sparkapisession.SparkApiSession', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sparkapisession.SparkApiSession', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SparkApiSession(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def previewDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapisession.SparkApiSession/previewDataset',
            sparkapi__session__pb2.PreviewDatasetRequest.SerializeToString,
            sparkapi__session__pb2.DatasetRowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def summarizeDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapisession.SparkApiSession/summarizeDataset',
            sparkapi__session__pb2.SummarizeDatasetRequest.SerializeToString,
            sparkapi__session__pb2.PysparkGeneralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def loadsDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapisession.SparkApiSession/loadsDataset',
            sparkapi__session__pb2.NewDatasetRequest.SerializeToString,
            sparkapi__session__pb2.PysparkGeneralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def runSql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapisession.SparkApiSession/runSql',
            sparkapi__session__pb2.SqlRequest.SerializeToString,
            sparkapi__session__pb2.PysparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapisession.SparkApiSession/createSession',
            sparkapi__session__pb2.NewSessionRequest.SerializeToString,
            sparkapi__session__pb2.NewSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
