# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkapi.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sparkapi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esparkapi.proto\x12\x08sparkapi\"Y\n\x16PysparkGeneralResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x14\n\x0c\x63olumns_json\x18\x03 \x01(\t\x12\x10\n\x08num_rows\x18\x04 \x01(\x05\"&\n\x12\x44\x61tasetRowResponse\x12\x10\n\x08row_json\x18\x01 \x01(\t\"A\n\x11NewDatasetRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x66_path\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x66_type\x18\x03 \x01(\t\"2\n\x15PreviewDatasetRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x32\xb0\x01\n\x08SparkApi\x12S\n\x0epreviewDataset\x12\x1f.sparkapi.PreviewDatasetRequest\x1a\x1c.sparkapi.DatasetRowResponse\"\x00\x30\x01\x12O\n\x0cloadsDataset\x12\x1b.sparkapi.NewDatasetRequest\x1a .sparkapi.PysparkGeneralResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sparkapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PYSPARKGENERALRESPONSE']._serialized_start=28
  _globals['_PYSPARKGENERALRESPONSE']._serialized_end=117
  _globals['_DATASETROWRESPONSE']._serialized_start=119
  _globals['_DATASETROWRESPONSE']._serialized_end=157
  _globals['_NEWDATASETREQUEST']._serialized_start=159
  _globals['_NEWDATASETREQUEST']._serialized_end=224
  _globals['_PREVIEWDATASETREQUEST']._serialized_start=226
  _globals['_PREVIEWDATASETREQUEST']._serialized_end=276
  _globals['_SPARKAPI']._serialized_start=279
  _globals['_SPARKAPI']._serialized_end=455
# @@protoc_insertion_point(module_scope)
