# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sparkapi_session.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sparkapi_session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sparkapi_session.proto\x12\x0fsparkapisession\"I\n\x12NewSessionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12session_server_pid\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"Y\n\x16PysparkGeneralResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x14\n\x0c\x63olumns_json\x18\x03 \x01(\t\x12\x10\n\x08num_rows\x18\x04 \x01(\x05\"&\n\x12\x44\x61tasetRowResponse\x12\x10\n\x08row_json\x18\x01 \x01(\t\"\x1f\n\x11NewSessionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"A\n\x11NewDatasetRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x66_path\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x66_type\x18\x03 \x01(\t\"2\n\x15PreviewDatasetRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x32\xaf\x02\n\x0fSparkApiSession\x12\x61\n\x0epreviewDataset\x12&.sparkapisession.PreviewDatasetRequest\x1a#.sparkapisession.DatasetRowResponse\"\x00\x30\x01\x12]\n\x0cloadsDataset\x12\".sparkapisession.NewDatasetRequest\x1a\'.sparkapisession.PysparkGeneralResponse\"\x00\x12Z\n\rcreateSession\x12\".sparkapisession.NewSessionRequest\x1a#.sparkapisession.NewSessionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sparkapi_session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWSESSIONRESPONSE']._serialized_start=43
  _globals['_NEWSESSIONRESPONSE']._serialized_end=116
  _globals['_PYSPARKGENERALRESPONSE']._serialized_start=118
  _globals['_PYSPARKGENERALRESPONSE']._serialized_end=207
  _globals['_DATASETROWRESPONSE']._serialized_start=209
  _globals['_DATASETROWRESPONSE']._serialized_end=247
  _globals['_NEWSESSIONREQUEST']._serialized_start=249
  _globals['_NEWSESSIONREQUEST']._serialized_end=280
  _globals['_NEWDATASETREQUEST']._serialized_start=282
  _globals['_NEWDATASETREQUEST']._serialized_end=347
  _globals['_PREVIEWDATASETREQUEST']._serialized_start=349
  _globals['_PREVIEWDATASETREQUEST']._serialized_end=399
  _globals['_SPARKAPISESSION']._serialized_start=402
  _globals['_SPARKAPISESSION']._serialized_end=705
# @@protoc_insertion_point(module_scope)
