# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sparkapi_pb2 as sparkapi__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sparkapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SparkApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createSession = channel.unary_unary(
                '/sparkapi.SparkApi/createSession',
                request_serializer=sparkapi__pb2.NewSessionRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.NewSessionResponse.FromString,
                _registered_method=True)
        self.previewDataset = channel.unary_stream(
                '/sparkapi.SparkApi/previewDataset',
                request_serializer=sparkapi__pb2.PreviewDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.RowStreamResponse.FromString,
                _registered_method=True)
        self.summarizeDataset = channel.unary_unary(
                '/sparkapi.SparkApi/summarizeDataset',
                request_serializer=sparkapi__pb2.SummarizeDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkActionlResponse.FromString,
                _registered_method=True)
        self.getParentSessionPlan = channel.unary_unary(
                '/sparkapi.SparkApi/getParentSessionPlan',
                request_serializer=sparkapi__pb2.PlanRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.getRebuildStatus = channel.unary_unary(
                '/sparkapi.SparkApi/getRebuildStatus',
                request_serializer=sparkapi__pb2.RebuildStatusRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.RebuildStatusResponse.FromString,
                _registered_method=True)
        self.rebuildSession = channel.unary_unary(
                '/sparkapi.SparkApi/rebuildSession',
                request_serializer=sparkapi__pb2.RebuildRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.PysparkTransformResponse.FromString,
                _registered_method=True)
        self.loadsDataset = channel.unary_unary(
                '/sparkapi.SparkApi/loadsDataset',
                request_serializer=sparkapi__pb2.LoadDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.loadFromSession = channel.unary_unary(
                '/sparkapi.SparkApi/loadFromSession',
                request_serializer=sparkapi__pb2.LoadFromSessionRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.addNode = channel.unary_unary(
                '/sparkapi.SparkApi/addNode',
                request_serializer=sparkapi__pb2.NodeAddRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.editNode = channel.unary_unary(
                '/sparkapi.SparkApi/editNode',
                request_serializer=sparkapi__pb2.NodeEditRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.removeNode = channel.unary_unary(
                '/sparkapi.SparkApi/removeNode',
                request_serializer=sparkapi__pb2.NodeRemovalRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)


class SparkApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def previewDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def summarizeDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getParentSessionPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getRebuildStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rebuildSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def loadsDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def loadFromSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def editNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SparkApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createSession': grpc.unary_unary_rpc_method_handler(
                    servicer.createSession,
                    request_deserializer=sparkapi__pb2.NewSessionRequest.FromString,
                    response_serializer=sparkapi__pb2.NewSessionResponse.SerializeToString,
            ),
            'previewDataset': grpc.unary_stream_rpc_method_handler(
                    servicer.previewDataset,
                    request_deserializer=sparkapi__pb2.PreviewDatasetRequest.FromString,
                    response_serializer=sparkapi__pb2.RowStreamResponse.SerializeToString,
            ),
            'summarizeDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.summarizeDataset,
                    request_deserializer=sparkapi__pb2.SummarizeDatasetRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkActionlResponse.SerializeToString,
            ),
            'getParentSessionPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.getParentSessionPlan,
                    request_deserializer=sparkapi__pb2.PlanRequest.FromString,
                    response_serializer=sparkapi__pb2.PlanResponse.SerializeToString,
            ),
            'getRebuildStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getRebuildStatus,
                    request_deserializer=sparkapi__pb2.RebuildStatusRequest.FromString,
                    response_serializer=sparkapi__pb2.RebuildStatusResponse.SerializeToString,
            ),
            'rebuildSession': grpc.unary_unary_rpc_method_handler(
                    servicer.rebuildSession,
                    request_deserializer=sparkapi__pb2.RebuildRequest.FromString,
                    response_serializer=sparkapi__pb2.PysparkTransformResponse.SerializeToString,
            ),
            'loadsDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.loadsDataset,
                    request_deserializer=sparkapi__pb2.LoadDatasetRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'loadFromSession': grpc.unary_unary_rpc_method_handler(
                    servicer.loadFromSession,
                    request_deserializer=sparkapi__pb2.LoadFromSessionRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'addNode': grpc.unary_unary_rpc_method_handler(
                    servicer.addNode,
                    request_deserializer=sparkapi__pb2.NodeAddRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'editNode': grpc.unary_unary_rpc_method_handler(
                    servicer.editNode,
                    request_deserializer=sparkapi__pb2.NodeEditRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'removeNode': grpc.unary_unary_rpc_method_handler(
                    servicer.removeNode,
                    request_deserializer=sparkapi__pb2.NodeRemovalRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sparkapi.SparkApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sparkapi.SparkApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SparkApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/createSession',
            sparkapi__pb2.NewSessionRequest.SerializeToString,
            sparkapi__pb2.NewSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def previewDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapi.SparkApi/previewDataset',
            sparkapi__pb2.PreviewDatasetRequest.SerializeToString,
            sparkapi__pb2.RowStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def summarizeDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/summarizeDataset',
            sparkapi__pb2.SummarizeDatasetRequest.SerializeToString,
            sparkapi__pb2.SparkActionlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getParentSessionPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/getParentSessionPlan',
            sparkapi__pb2.PlanRequest.SerializeToString,
            sparkapi__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getRebuildStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/getRebuildStatus',
            sparkapi__pb2.RebuildStatusRequest.SerializeToString,
            sparkapi__pb2.RebuildStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rebuildSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/rebuildSession',
            sparkapi__pb2.RebuildRequest.SerializeToString,
            sparkapi__pb2.PysparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def loadsDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/loadsDataset',
            sparkapi__pb2.LoadDatasetRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def loadFromSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/loadFromSession',
            sparkapi__pb2.LoadFromSessionRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/addNode',
            sparkapi__pb2.NodeAddRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def editNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/editNode',
            sparkapi__pb2.NodeEditRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def removeNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/removeNode',
            sparkapi__pb2.NodeRemovalRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
