# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sparkapi_pb2 as sparkapi__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sparkapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SparkApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createSession = channel.unary_unary(
                '/sparkapi.SparkApi/createSession',
                request_serializer=sparkapi__pb2.NewSessionRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.NewSessionResponse.FromString,
                _registered_method=True)
        self.loadSessions = channel.unary_stream(
                '/sparkapi.SparkApi/loadSessions',
                request_serializer=sparkapi__pb2.Empty.SerializeToString,
                response_deserializer=sparkapi__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.previewDataset = channel.unary_stream(
                '/sparkapi.SparkApi/previewDataset',
                request_serializer=sparkapi__pb2.PreviewDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.DatasetResponse.FromString,
                _registered_method=True)
        self.summarizeDataset = channel.unary_unary(
                '/sparkapi.SparkApi/summarizeDataset',
                request_serializer=sparkapi__pb2.SummarizeDatasetRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkActionlResponse.FromString,
                _registered_method=True)
        self.getSessionStatus = channel.unary_unary(
                '/sparkapi.SparkApi/getSessionStatus',
                request_serializer=sparkapi__pb2.SessionStatusRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.submit_LoadDatasetNode = channel.unary_stream(
                '/sparkapi.SparkApi/submit_LoadDatasetNode',
                request_serializer=sparkapi__pb2.LoadDatasetNodeRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.submit_LoadFromSessionNode = channel.unary_unary(
                '/sparkapi.SparkApi/submit_LoadFromSessionNode',
                request_serializer=sparkapi__pb2.LoadFromSessionNodeRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.submit_FilterNode = channel.unary_unary(
                '/sparkapi.SparkApi/submit_FilterNode',
                request_serializer=sparkapi__pb2.FilterNodeRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.submit_AddColumnNode = channel.unary_stream(
                '/sparkapi.SparkApi/submit_AddColumnNode',
                request_serializer=sparkapi__pb2.AddColumnNodeRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.submit_JoinNode = channel.unary_unary(
                '/sparkapi.SparkApi/submit_JoinNode',
                request_serializer=sparkapi__pb2.JoinNodeRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.submit_TableNode = channel.unary_unary(
                '/sparkapi.SparkApi/submit_TableNode',
                request_serializer=sparkapi__pb2.AddTableNodeRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.submit_HistogramNode = channel.unary_unary(
                '/sparkapi.SparkApi/submit_HistogramNode',
                request_serializer=sparkapi__pb2.AddHistogramNodeRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.removeNode = channel.unary_stream(
                '/sparkapi.SparkApi/removeNode',
                request_serializer=sparkapi__pb2.NodeRemovalRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)
        self.toggleNode = channel.unary_stream(
                '/sparkapi.SparkApi/toggleNode',
                request_serializer=sparkapi__pb2.NodeToggleRequest.SerializeToString,
                response_deserializer=sparkapi__pb2.SparkTransformResponse.FromString,
                _registered_method=True)


class SparkApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def loadSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def previewDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def summarizeDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_LoadDatasetNode(self, request, context):
        """load node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_LoadFromSessionNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_FilterNode(self, request, context):
        """filter node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_AddColumnNode(self, request, context):
        """add column node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_JoinNode(self, request, context):
        """join node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_TableNode(self, request, context):
        """table node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_HistogramNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeNode(self, request, context):
        """all nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def toggleNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SparkApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createSession': grpc.unary_unary_rpc_method_handler(
                    servicer.createSession,
                    request_deserializer=sparkapi__pb2.NewSessionRequest.FromString,
                    response_serializer=sparkapi__pb2.NewSessionResponse.SerializeToString,
            ),
            'loadSessions': grpc.unary_stream_rpc_method_handler(
                    servicer.loadSessions,
                    request_deserializer=sparkapi__pb2.Empty.FromString,
                    response_serializer=sparkapi__pb2.SessionResponse.SerializeToString,
            ),
            'previewDataset': grpc.unary_stream_rpc_method_handler(
                    servicer.previewDataset,
                    request_deserializer=sparkapi__pb2.PreviewDatasetRequest.FromString,
                    response_serializer=sparkapi__pb2.DatasetResponse.SerializeToString,
            ),
            'summarizeDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.summarizeDataset,
                    request_deserializer=sparkapi__pb2.SummarizeDatasetRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkActionlResponse.SerializeToString,
            ),
            'getSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getSessionStatus,
                    request_deserializer=sparkapi__pb2.SessionStatusRequest.FromString,
                    response_serializer=sparkapi__pb2.StatusResponse.SerializeToString,
            ),
            'submit_LoadDatasetNode': grpc.unary_stream_rpc_method_handler(
                    servicer.submit_LoadDatasetNode,
                    request_deserializer=sparkapi__pb2.LoadDatasetNodeRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'submit_LoadFromSessionNode': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_LoadFromSessionNode,
                    request_deserializer=sparkapi__pb2.LoadFromSessionNodeRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'submit_FilterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_FilterNode,
                    request_deserializer=sparkapi__pb2.FilterNodeRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'submit_AddColumnNode': grpc.unary_stream_rpc_method_handler(
                    servicer.submit_AddColumnNode,
                    request_deserializer=sparkapi__pb2.AddColumnNodeRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'submit_JoinNode': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_JoinNode,
                    request_deserializer=sparkapi__pb2.JoinNodeRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'submit_TableNode': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_TableNode,
                    request_deserializer=sparkapi__pb2.AddTableNodeRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'submit_HistogramNode': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_HistogramNode,
                    request_deserializer=sparkapi__pb2.AddHistogramNodeRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'removeNode': grpc.unary_stream_rpc_method_handler(
                    servicer.removeNode,
                    request_deserializer=sparkapi__pb2.NodeRemovalRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
            'toggleNode': grpc.unary_stream_rpc_method_handler(
                    servicer.toggleNode,
                    request_deserializer=sparkapi__pb2.NodeToggleRequest.FromString,
                    response_serializer=sparkapi__pb2.SparkTransformResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sparkapi.SparkApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sparkapi.SparkApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SparkApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/createSession',
            sparkapi__pb2.NewSessionRequest.SerializeToString,
            sparkapi__pb2.NewSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def loadSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapi.SparkApi/loadSessions',
            sparkapi__pb2.Empty.SerializeToString,
            sparkapi__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def previewDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapi.SparkApi/previewDataset',
            sparkapi__pb2.PreviewDatasetRequest.SerializeToString,
            sparkapi__pb2.DatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def summarizeDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/summarizeDataset',
            sparkapi__pb2.SummarizeDatasetRequest.SerializeToString,
            sparkapi__pb2.SparkActionlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/getSessionStatus',
            sparkapi__pb2.SessionStatusRequest.SerializeToString,
            sparkapi__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_LoadDatasetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapi.SparkApi/submit_LoadDatasetNode',
            sparkapi__pb2.LoadDatasetNodeRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_LoadFromSessionNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/submit_LoadFromSessionNode',
            sparkapi__pb2.LoadFromSessionNodeRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_FilterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/submit_FilterNode',
            sparkapi__pb2.FilterNodeRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_AddColumnNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapi.SparkApi/submit_AddColumnNode',
            sparkapi__pb2.AddColumnNodeRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_JoinNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/submit_JoinNode',
            sparkapi__pb2.JoinNodeRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_TableNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/submit_TableNode',
            sparkapi__pb2.AddTableNodeRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submit_HistogramNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sparkapi.SparkApi/submit_HistogramNode',
            sparkapi__pb2.AddHistogramNodeRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def removeNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapi.SparkApi/removeNode',
            sparkapi__pb2.NodeRemovalRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def toggleNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sparkapi.SparkApi/toggleNode',
            sparkapi__pb2.NodeToggleRequest.SerializeToString,
            sparkapi__pb2.SparkTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
