[build-system]
requires = ["setuptools>=64", "wheel", "grpcio-tools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyspark_api"
version = "0.3"
requires-python = "==3.11.10"
dependencies = [
    "grpcio",
    "grpcio-tools",
    "pyspark",
    "pandas",
    "asyncio",
    "pytest",
    "requests",
    "ruff",
]

[tool.setuptools]
package-dir = { "" = "lib" }

[tool.setuptools.packages.find]
where = ["lib"]


[tool.ruff]
target-version = "py311"
line-length = 140
indent-width = 4

exclude = [
    ".bzr",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "dist",
    ".*venv",
    "setup.py",
    "*_pb2*.py",
]


[tool.ruff.format]
quote-style = "single"
line-ending = "auto"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
select = [
    "I",   # isort
    "E",   # pycodestyle
    "D",   # pydocstyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
]
ignore = [
    "E203",   # whitespace before ",", ";", or ":"
    "D100",
    "D101",
    "D102",   # Missing docstring in public method
    "D103",
    "D104",   # Disable package and module docstrings
    "D105",
    "D106",
    "D107",
    "UP045",
    "N812",   # Imports as uppercase (e.g., functions as F)
    "COM812", # Missing trailing comma
    "RET504", # Unnecessary assignment to `df` before `return` statement
    "RUF100", # Unused `noqa` directive (unknown: `E814`) - not aligned with Foundry's checks
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
combine-as-imports = true
