syntax = "proto3";

package sparkapi;

service SparkApi {
    rpc createSession(NewSessionRequest) returns (NewSessionResponse) {}
    
    rpc previewDataset(PreviewDatasetRequest) returns (stream DatasetResponse) {}
    rpc summarizeDataset(SummarizeDatasetRequest) returns (SparkActionlResponse) {}
    rpc getSessionStatus(SessionStatusRequest) returns (StatusResponse) {}

    // load node
    rpc submit_LoadDatasetNode(LoadDatasetNodeRequest) returns (stream SparkTransformResponse) {}
    rpc submit_LoadFromSessionNode(LoadFromSessionNodeRequest) returns (SparkTransformResponse) {}
    
    // filter node
    rpc submit_FilterNode(FilterNodeRequest) returns (SparkTransformResponse) {}
    
    // add column node
    rpc submit_NewColumnNode(NewColumnNodeRequest) returns (stream SparkTransformResponse) {}
    
    // join node
    rpc submit_JoinNode(JoinNodeRequest) returns (SparkTransformResponse) {}
    
    // table node
    rpc submit_TableNode(AddTableNodeRequest) returns (SparkTransformResponse) {}
    rpc submit_HistogramNode(AddHistogramNodeRequest) returns (SparkTransformResponse) {}
    
    // all nodes
    rpc removeNode(NodeRemovalRequest) returns (stream SparkTransformResponse) {}
    rpc toggleNode(NodeToggleRequest) returns (stream SparkTransformResponse) {}
}


// --- Responses ---

message NewSessionResponse {
    string session_id = 1;
    string msg = 2;
}

message SparkActionlResponse {
    string session_id = 1;
    string msg = 2;
    string columns = 3;
    string schema = 4;
    int32 count = 5;
}

message Column {
    string name = 1;
    string dtype = 2;
}

message InvalidState {
    bool active = 1;
    string error_msg = 2;
}

message SparkTransformResponse {
    string session_id = 1;
    string node_id = 2;
    InvalidState invalid_state = 3;
    bool active = 4;
    repeated Column columns = 5;
}

message DatasetResponse {
    string data = 1;
}

message StatusResponse {
    string session_id = 1;
    bool rebuild_recommendation = 2;
    string cause = 3;
}


// --- Requests ---

message NewSessionRequest {
    string id = 1;
    string name = 2;
}

message CsvInput {
    string delimiter = 1;
    bool include_header = 2;
    string path = 3;
}

message JsonInput {
    bool multiline = 1;
    string path = 2;
}

message ParquetInput {
    string path = 1;
}

message LoadDatasetNodeRequest {
    string session_id = 1;
    oneof user_input {
        CsvInput csv = 2;
        JsonInput json = 3;
        ParquetInput parquet = 4;
    }
}

message SessionInput {
    string session_id = 1;
}


message PreviewDatasetRequest {
    string session_id = 1;
    string node_id = 2;
    int32 limit = 3;
}

message SummarizeDatasetRequest {
    string session_id = 1;
    string node_id = 2;
}

message FilterNodeRequest {
    string session_id = 1;
    string node_id = 2;
    string prev_node_id = 3;
    repeated string expressions = 4;
    string matching = 5;    // and, or, default=None
}

message AddTableNodeRequest {
    string session_id = 1;
    string node_id = 2;
    string prev_node_id = 3;
}

message AddHistogramNodeRequest {
    string session_id = 1;
    string node_id = 2;
    string prev_node_id = 3;
    string y_axis_col = 4;
    string order_by = 5;
    string sort_by = 6;
    string expression = 7;
}

message AddColumnExpression {
    string expression = 1;
    string col_name = 2;
}

message NewColumnNodeRequest {
    string session_id = 1;
    string node_id = 2;
    string prev_node_id = 3;
    repeated AddColumnExpression expressions = 4;
}

message JoinParams {
    string join_relation = 1;
    repeated string columns_to_keep = 2;
    repeated string columns_to_add = 3;
    string prefix_for_added_columns = 4;
    repeated string join_criteria = 5;
    string criteria_matching = 6;
}

message JoinNodeRequest {
    string session_id = 1;
    string node_id = 2;
    string prev_node_id = 3;
    oneof input_metadata {
        CsvInput csv = 4;
        JsonInput json = 5;
        ParquetInput parquet = 6;
        SessionInput session = 7;
    }
    JoinParams joinParams = 8;
}

message NodeRemovalRequest {
    string session_id = 1;
    string node_id = 2;
}

message NodeToggleRequest {
    string session_id = 1;
    string node_id = 2;
    bool toggle = 3;
}

message LoadFromSessionNodeRequest {
    string session_id = 1;
    string input_session_id = 2;
}

message SessionStatusRequest {
    string session_id = 1;
}

