syntax = "proto3";

package sparkapisession;

service SparkApiSession {
    rpc previewDataset(PreviewDatasetRequest) returns (stream DatasetRowResponse) {}
    rpc loadsDataset(NewDatasetRequest) returns (PysparkGeneralResponse) {}
    rpc filterDataset(FilterDatasetRequest) returns (PysparkTransformResponse) {}
    rpc createSession(NewSessionRequest) returns (NewSessionResponse) {}
}


// --- Responses ---

message NewSessionResponse {
    string id = 1;
    string session_server_pid = 2;
    string msg = 3;
}

message PysparkGeneralResponse {
    string id = 1;
    string msg = 2;
    string columns_json = 3;
    int32 num_rows = 4;
}

message PysparkTransformResponse {
    string id = 1;
    string msg = 2;
}

message DatasetRowResponse {
    string row_json = 1;
}


// --- Requests ---

message FilterDatasetRequest {
    string id = 1;
    string filter_sql = 2;
}

message NewSessionRequest {
    string id = 1;
}

message NewDatasetRequest {
    string id = 1;
    string df_path = 2;
    string df_type = 3;
}

message PreviewDatasetRequest {
    string id = 1;
    int32 limit = 2;
}