syntax = "proto3";

package sparkapisession;

service SparkApiSession {
    rpc createSession(NewSessionRequest) returns (NewSessionResponse) {}
    rpc previewDataset(PreviewDatasetRequest) returns (stream DatasetRowResponse) {}
    rpc summarizeDataset(SummarizeDatasetRequest) returns (PysparkGeneralResponse) {}
    rpc rebuildSession(RebuildRequest) returns (PysparkTransformResponse) {}
    rpc notifyMasterInputChange(MasterInputChangeNotificationRequest) returns (MasterInputChangeNotificationResponse) {}
    rpc getRebuildStatus(RebuildStatusRequest) returns (RebuildStatusResponse) {}
    
    rpc loadsDataset(NewDatasetRequest) returns (PysparkGeneralResponse) {}
    rpc loadFromSession(DatasetFromSessionRequest) returns (PysparkTransformResponse) {}

    rpc addSql(SqlRequest) returns (PysparkTransformSqlResponse) {}
}


// --- Responses ---

message NewSessionResponse {
    string id = 1;
    string session_server_pid = 2;
    string msg = 3;
}

message PysparkGeneralResponse {
    string session_id = 1;
    string msg = 2;
    string columns_json = 3;
    string schema_tree = 4;
    int32 num_rows = 5;
}

message PysparkTransformResponse {
    string session_id = 1;
    string msg = 2;
}

message PysparkTransformSqlResponse {
    string session_id = 1;
    string msg = 2;
    bytes planner = 3;
}

message DatasetRowResponse {
    string row_json = 1;
}

message MasterInputChangeNotificationResponse {
    string id = 1;
    bool verification = 2;
}

message RebuildStatusResponse {
    string id = 1;
    bool rebuild_status = 2;
}


// --- Requests ---

message NewSessionRequest {
    string id = 1;
}

message NewDatasetRequest {
    string session_id = 1;
    string df_path = 2;
    string df_type = 3;
}

message PreviewDatasetRequest {
    string id = 1;
    int32 limit = 2;
}

message SummarizeDatasetRequest {
    string session_id = 1;
    string node_id = 2;
    bytes planner = 3;
}

message DatasetFromSessionRequest {
    string id = 1;
    string input_id = 2;
}

message SqlRequest {
    string session_id = 1;
    string node_id = 2;
    string previous_node_id = 3;
    string query_type = 4;
    string query = 5;
    string query_params_json = 6;
    bytes planner = 7;
}

message RebuildRequest {
    string session_id = 1;
    bytes planner = 2;
}

message MasterInputChangeNotificationRequest {
    string id = 1;
}

message RebuildStatusRequest {
    string id = 1;
}
