name: Python Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11.10"

      - name: Install spark_api dependencies
        run: cd spark_api && uv sync && uv pip install -e .
      
      - name: Install service dependencies
        run: cd service && uv sync && uv pip install -e .

      - name: Start services
        run: |
          chmod +x start-backend.sh
          ./start-backend.sh &
          sleep 20

      - name: Run tests for API
        run: cd service && uv run pytest tests/test_api.py -s

      - name: Run tests for use cases
        run: cd spark_api && uv run pytest tests/test_use_cases.py -s

      - name: Stop services
        if: always()
        run: |
          [ -f spark_api.pid ] && kill $(cat spark_api.pid) || true
          [ -f service.pid ] && kill $(cat service.pid) || true
